name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract ZIP
        run: unzip your-file.zip -d extracted
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build APK
        run: |
          cd extracted
          # إذا كان الملف المستخرج هو مشروع Android
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          # إذا كان مجرد ملفات
          else
            zip -r unsigned.apk *
            $ANDROID_HOME/build-tools/30.0.3/zipalign -v 4 unsigned.apk aligned.apk
            # هذا سيتطلب مفتاح توقيع، ولكن يمكننا إنشاء مفتاح للاختبار
            keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
            $ANDROID_HOME/build-tools/30.0.3/apksigner sign --ks debug.keystore --ks-pass pass:android --out final.apk aligned.apk
          fi
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            extracted/app/build/outputs/apk/debug/*.apk
            extracted/final.apk
